using LMT.Api.Data;
using LMT.Api.DTOs;

namespace LMT.Api.Interfaces
{
    public interface IAuthService
    {
        Task<TokenResponse> AuthenticateUserAsync(LoginRequest loginRequest);
        Task<string> RegisterAsync(RegisterRequest registerRequest);
        Task AccountConfirmation(string email, int code);
        Task<string> SendReAccountConfirmation(string email);
        Task<bool> EditUserAsync(ApplicationUser editUserRequest);
        Task<TokenResponse> RefreshToken(TokenModel tokenModel);
        Task RevokeAsync(string refreshToken);
        Task RevokeAllAsync();
        Task<bool> ForgotPasswordAsync(string email);
        Task ResetPasswordAsync(ResetPasswordRequest resetPasswordRequest);
        Task<bool> ChangePasswordAsync(ChangePasswordRequest changePasswordRequest);
        Task<List<UserListDTO>> GetUserListAsync();
        Task<bool> DeleteUserAsync(string userId);
        Task<ApplicationUser> GetUserByIdAsync(string userId);
        Task<IEnumerable<GetRegisteredFieldOfficersDTO>> GetRegisteredUsersListAsync(string userId);
        Task<bool> SendLoginDetailsEmailAsync(ApplicationUser user, string autoGeneratedPassword);
        Task<bool> SendVerificationCodeEmailAsync(ApplicationUser user, string emailCode);
    }
}
